version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s

  gateway:
    build:
      context: ./gateway-ms
      dockerfile: Dockerfile
    container_name: gateway-ms
    environment:
      LISTEN_PORT: ${GATEWAY_LISTEN_PORT}
      USER_MS_HOST: ${USER_MS_HOST}
      USER_MS_PORT: ${USER_MS_PORT}
      TODO_MS_HOST: ${TODO_MS_HOST}
      TODO_MS_PORT: ${TODO_MS_PORT}
    ports:
      - "${GATEWAY_LISTEN_PORT}:8080"
    depends_on:
      - user-ms
      - todo-ms
    networks:
      - shared_network

  user-ms:
    build:
      context: ./user-ms
      dockerfile: Dockerfile
    container_name: user-ms
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${USER_MS_DB_NAME}
      LISTEN_PORT: ${USER_MS_LISTEN_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network

  todo-ms:
    build:
      context: ./to-do-ms
      dockerfile: Dockerfile
    container_name: todo-ms
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${TODO_MS_DB_NAME}
      LISTEN_PORT: ${TODO_MS_LISTEN_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared_network

volumes:
  postgres_data:
    driver: local

networks:
  shared_network:
    driver: bridge
